### ISSUE TITLE
shelf_multipart not working to Big File

### ISSUE THREAD

**Issue by wengxianxun** [simolus3/goodies.dart#5]
shelf_multipart not working to Big File, like i have a    2GB video file, i cant use shelf_multipart read file data.

**Comment by simolus3** [comment]
Thanks for the report, I'll take a look. Can you share a bit more details (or simple code snippets) on what you're doing with the file on the server, how you're creating the request and what's going wrong? That will make it easier for me to reproduce and fix the problem.

**Comment by wengxianxun** [comment]
this is demo https://github.com/wengxianxun/shelf_demo.git
1. run demo  and [start server]
![Screenshot_20240305_090636_com example shelf_demo](https://github.com/simolus3/goodies.dart/assets/831898/19422038-549c-4aec-a7cf-20a8799a9076)

2. Accessing in your computer browser http://192.168.31.46:8080/assets/upload.html
<img width="589" alt="image" src="https://github.com/simolus3/goodies.dart/assets/831898/3d0efb41-5a51-4941-86be-0b26b08b13af">

3. select a big file like this and upload
<img width="1636" alt="image" src="https://github.com/simolus3/goodies.dart/assets/831898/df7a3a95-efdc-4d96-9e0b-dc9153a432a9">

4.Wait for a moment to return error
<img width="609" alt="image" src="https://github.com/simolus3/goodies.dart/assets/831898/c355af4b-b646-442c-841c-7abfaadca4fb">

**Comment by wengxianxun** [comment]
This is the main code for receiving files
<img width="745" alt="image" src="https://github.com/simolus3/goodies.dart/assets/831898/fb7ccecf-cb07-4799-988f-eb9919116796">

**Comment by wengxianxun** [comment]
@simolus3  Please review the above answers. Thank you

**Comment by simolus3** [comment]
This works fine for me even with multi-GB files. I guess what's happening here is that the device you're running the code on is out of memory. There's an obvious reason for that, you're collecting the entire file in memory. You can use streams to disk to avoid that:

```dart
if (formData.name == 'uploadfile') {
  var totalLength = 0;
  var tempDir = await getTemporaryDirectory();
  var file = File('${tempDir.path}/${formData.filename}');

  await formData.part.pipe(file.openWrite());

  print("${file.path}");
  totalLength += await file.length();
  print("长度:${totalLength}");
}
```

**Comment by wengxianxun** [comment]
> This works fine for me even with multi-GB files. I guess what's happening here is that the device you're running the code on is out of memory. There's an obvious reason for that, you're collecting the entire file in memory. You can use streams to disk to avoid that:
> 
> ```dart
> if (formData.name == 'uploadfile') {
>   var totalLength = 0;
>   var tempDir = await getTemporaryDirectory();
>   var file = File('${tempDir.path}/${formData.filename}');
> 
>   await formData.part.pipe(file.openWrite());
> 
>   print("${file.path}");
>   totalLength += await file.length();
>   print("长度:${totalLength}");
> }
> ```

is working now. thank you very much.
